#!/usr/bin/env node
/**
 * postbuild.mjs — Creates a Vercel Build Output API v3 structure from the
 * TanStack Start SSR build output. Runs automatically after `npm run build`
 * via the "postbuild" script in package.json.
 *
 * Uses Vercel Node.js serverless runtime (NOT Edge) because the SSR bundle
 * depends on Node.js-only packages (React, Firebase, lucide-react, etc.)
 * which are blocked in the Edge sandbox.
 *
 * Output layout:
 *   .vercel/output/
 *     config.json                    ← routing rules (Vercel v3)
 *     static/assets/                 ← hashed CSS/JS/images (immutable cache)
 *     functions/index.func/
 *       .vc-config.json              ← nodejs20.x runtime declaration
 *       index.js                     ← Node.js http handler (bridges Fetch API ↔ http)
 *       server.js                    ← compiled TanStack SSR server
 *       assets/                      ← all server asset chunks
 */

import { mkdirSync, copyFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();
const OUT = join(ROOT, ".vercel/output");
const STATIC = join(OUT, "static");
const FUNC = join(OUT, "functions/index.func");

// ── helpers ───────────────────────────────────────────────────────────────────
function mkdirs(...dirs) {
  dirs.forEach((d) => mkdirSync(d, { recursive: true }));
}

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const s = join(src, entry);
    const d = join(dest, entry);
    statSync(s).isDirectory() ? copyDir(s, d) : copyFileSync(s, d);
  }
}

// ── 1. Scaffold output dirs ───────────────────────────────────────────────────
mkdirs(STATIC, FUNC, join(FUNC, "assets"));
console.log("📁  Created .vercel/output structure");

// ── 2. Copy client static assets (JS, CSS, images) ───────────────────────────
copyDir(join(ROOT, "dist/client/assets"), join(STATIC, "assets"));
console.log("📦  Copied client assets → .vercel/output/static/assets/");

// ── 3. Copy the entire server bundle into the Node.js function folder ─────────
copyFileSync(join(ROOT, "dist/server/server.js"), join(FUNC, "server.js"));
copyDir(join(ROOT, "dist/server/assets"), join(FUNC, "assets"));
console.log("🖥️   Copied server bundle → .vercel/output/functions/index.func/");

// ── 4. Write the Node.js serverless function entrypoint ──────────────────────
// TanStack Start server exports: { fetch(Request, env, ctx) => Promise<Response> }
// Vercel Node.js functions receive:  (req: IncomingMessage, res: ServerResponse)
// This wrapper bridges between the two interfaces.
writeFileSync(
  join(FUNC, "index.js"),
  `// Auto-generated by postbuild.mjs — DO NOT EDIT
// Bridges Vercel Node.js http handler ↔ TanStack Start Fetch API SSR server
import server from "./server.js";

export default async function handler(req, res) {
  // Reconstruct the full URL from Vercel proxy headers
  const protocol = req.headers["x-forwarded-proto"] || "https";
  const host = req.headers["x-forwarded-host"] || req.headers.host || "localhost";
  const url = new URL(req.url, \`\${protocol}://\${host}\`);

  // Convert Node.js headers object to Fetch API Headers
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value !== undefined) {
      headers.set(key, Array.isArray(value) ? value.join(", ") : value);
    }
  }

  // Buffer request body for non-GET requests (forms, API calls, etc.)
  let body = undefined;
  const method = (req.method || "GET").toUpperCase();
  if (method !== "GET" && method !== "HEAD") {
    const chunks = [];
    for await (const chunk of req) {
      chunks.push(chunk);
    }
    if (chunks.length > 0) {
      body = Buffer.concat(chunks);
    }
  }

  // Build the Fetch API Request
  const fetchRequest = new Request(url.toString(), { method, headers, body });

  try {
    // Call the TanStack Start SSR handler
    const response = await server.fetch(fetchRequest, {}, {});

    // Forward status code
    res.statusCode = response.status;

    // Forward response headers
    for (const [key, value] of response.headers.entries()) {
      res.setHeader(key, value);
    }

    // Stream response body back to client
    if (response.body) {
      const reader = response.body.getReader();
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        res.write(value);
      }
    }
    res.end();
  } catch (err) {
    console.error("[SSR] Unhandled error:", err);
    res.statusCode = 500;
    res.setHeader("content-type", "text/plain");
    res.end("Internal Server Error");
  }
}
`,
);
console.log("⚡  Wrote Node.js serverless function entrypoint");

// ── 5. Write .vc-config.json — Node.js runtime (NOT edge) ────────────────────
writeFileSync(
  join(FUNC, ".vc-config.json"),
  JSON.stringify(
    {
      runtime: "nodejs20.x",
      handler: "index.js",
      launcherType: "Nodejs",
      shouldAddHelpers: false,
      maxDuration: 30,
    },
    null,
    2,
  ),
);

// ── 6. Write the Vercel output routing config ─────────────────────────────────
writeFileSync(
  join(OUT, "config.json"),
  JSON.stringify(
    {
      version: 3,
      routes: [
        // Serve hashed static assets directly with permanent immutable cache headers
        {
          src: "^/assets/(.+)$",
          headers: { "cache-control": "public, max-age=31536000, immutable" },
          continue: true,
        },
        // All other requests → SSR Node.js serverless function
        { src: "^/(.*)$", dest: "/index" },
      ],
    },
    null,
    2,
  ),
);
console.log("✅  .vercel/output/config.json written");
console.log("\n🚀  Vercel Build Output API v3 (Node.js) ready!");
