#!/usr/bin/env node
/**
 * postbuild.mjs — Creates a Vercel Build Output API v3 structure from the
 * TanStack Start SSR build output. Runs automatically after `npm run build`
 * via the "postbuild" script in package.json.
 *
 * Output layout:
 *   .vercel/output/
 *     config.json                    ← routing rules (Vercel v3)
 *     static/assets/                 ← hashed CSS/JS/images (immutable cache)
 *     functions/index.func/          ← Edge Function for SSR
 *       .vc-config.json
 *       index.js                     ← entrypoint wrapper
 *       server.js                    ← compiled TanStack SSR server
 *       assets/                      ← all server asset chunks
 */

import { mkdirSync, copyFileSync, writeFileSync, readdirSync, statSync, readFileSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();
const OUT = join(ROOT, ".vercel/output");
const STATIC = join(OUT, "static");
const FUNC = join(OUT, "functions/index.func");

// ── helpers ───────────────────────────────────────────────────────────────────
function mkdirs(...dirs) {
  dirs.forEach((d) => mkdirSync(d, { recursive: true }));
}

function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const s = join(src, entry);
    const d = join(dest, entry);
    statSync(s).isDirectory() ? copyDir(s, d) : copyFileSync(s, d);
  }
}

// ── 1. Scaffold output dirs ───────────────────────────────────────────────────
mkdirs(STATIC, FUNC, join(FUNC, "assets"));
console.log("📁  Created .vercel/output structure");

// ── 2. Copy client static assets (JS, CSS, images) ───────────────────────────
copyDir(join(ROOT, "dist/client/assets"), join(STATIC, "assets"));
console.log("📦  Copied client assets → .vercel/output/static/assets/");

// ── 3. Copy the entire server bundle into the edge function folder ────────────
copyFileSync(join(ROOT, "dist/server/server.js"), join(FUNC, "server.js"));
copyDir(join(ROOT, "dist/server/assets"), join(FUNC, "assets"));
console.log("🖥️   Copied server bundle → .vercel/output/functions/index.func/");

// ── 4. Write the thin edge function entrypoint ───────────────────────────────
// dist/server/server.js exports: `export default { fetch(req, env, ctx) }`
// Vercel Edge Functions expect: `export default function(request) → Response`
writeFileSync(
  join(FUNC, "index.js"),
  `// Auto-generated by postbuild.mjs — DO NOT EDIT
import server from "./server.js";
export default (request) => server.fetch(request, {}, {});
export const config = { runtime: "edge" };
`,
);
console.log("⚡  Wrote edge function entrypoint");

// ── 5. Write the Vercel function config ──────────────────────────────────────
writeFileSync(
  join(FUNC, ".vc-config.json"),
  JSON.stringify({ runtime: "edge", entrypoint: "index.js" }, null, 2),
);

// ── 6. Write the global Vercel output config (routing rules) ─────────────────
writeFileSync(
  join(OUT, "config.json"),
  JSON.stringify(
    {
      version: 3,
      routes: [
        // Serve hashed static assets with permanent immutable cache headers
        {
          src: "^/assets/(.+)$",
          headers: { "cache-control": "public, max-age=31536000, immutable" },
          continue: true,
        },
        // Route all other requests through the SSR edge function
        { src: "^/(.*)$", dest: "/index" },
      ],
    },
    null,
    2,
  ),
);
console.log("✅  vercel.output/config.json written");
console.log("\n🚀  Vercel Build Output API v3 ready — deploy with `vercel --prebuilt`");
